stages:
  - deploy

production deploy:
  stage: deploy
  before_script:
    # Install jq (https://stedolan.github.io/jq/download/)
    - apt-get update -y && apt-get install -y jq

    - sprint_branches_count=$(./count-sprint-branches.sh)

    # Debug statements
    - echo $sprint_branches_count
    - echo $CI_JOB_MANUAL
    - echo [[ $sprint_branches_count -gt 1 ]]
    - curl --header "Authorization:Bearer $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/branches?search=^sprint-"

    # If not triggered manually & have more than 1 sprint branch, exit early with 0 (success code)
    - if [[ $CI_JOB_MANUAL != true && $sprint_branches_count -gt 1 ]]; then exit 0; fi
  script:
    - echo "Im deploying :-)"
